FROM python:3.10-slim

RUN pip install --upgrade pip
RUN pip install pipenv

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY ["main.py", "scaler.pickle", "model.pickle", "col.pickle", "col_scaler.pickle", "./"]

EXPOSE 8000

ENTRYPOINT ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]